<?php
include './header.php';
include './class/db_connect.php';                        
?>
        <!-- page content -->
        <div class="right_col" role="main">
         
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="dashboard_graph">

                <div class="row x_title">
                  <div class="col-md-9">
                    <h3>REQUISITION APPROVAL <small>Departmental requisition slip final approval</small></h3>
                  </div>
                 <div class="col-md-6"></div>
                </div>
                <div class="x_title">
                    <h2>Slip Details <small>submit to see more details</small></h2>
                    <div class="clearfix"></div>
                  </div>
                 <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-6" >Slip No
                        </label>
                        <div class="col-md-2 col-sm-2 col-xs-6">
                            <input type="text" id="slip_no" name="slip_no" readonly=" " class="form-control col-md-7 col-xs-12" value="<?=$_GET['slipno']?>">
                        </div>
                       <label class="control-label col-md-2 col-sm-2 col-xs-6" >Department
                        </label>
                        <div class="col-md-2 col-sm-2 col-xs-6">
                            <input type="text" id="dept" name="dept" readonly=" " class="form-control col-md-7 col-xs-12" value="<?=$_GET['dept']?>">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="generated_by">Generated By
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <input type="text" id="generated by" name="generated_by" readonly="" value="<?=$_GET['gby']?>" class="form-control col-md-7 col-xs-12">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="generated_by_desg" class="control-label col-md-3 col-sm-3 col-xs-12">Generated By Designation:</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input id="generated_by_desg" class="form-control col-md-7 col-xs-12" readonly="" value="<?=$_GET['desg']?>" type="text" name="generated_for">
                        </div>
                      </div>
                      <div class="ln_solid"></div>
                      
                    </form> 
                  <!--div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                   <center> <button type="submit" class="btn btn-info" >View Items</button></center> 
                        </div-->
                  <div id="req_table_details">
                  <div class="x_title">
                    <h2>Item Details <small>slip item details</small></h2>
                    <div class="clearfix"></div>
                  </div>
                <!--div class="col-md-7 col-sm-7 col-xs-12"-->
                  <div class="x_content">
                    <div class="table-responsive" >
                      <table class="table table-striped jambo_table">
                        <thead>
                          <tr class="headings">
                            <!--th>
                                Select
                            </th-->
                            <th class="column-title">Serial No </th>
                            <th class="column-title">Item Name </th>
                            <th class="column-title">Item Maker </th>
                            <th class="column-title">Description </th>
                            <th class="column-title">Quantity </th>
                            <th class="column-title">Available Stock</th>
                            <th class="column-title">Unit </th>
                            <th class="column-title">Total Stock</th>
                            <th class="column-title">More Details</th>
                            <th class="column-title">Dispatch</th>
                            <th class="column-title">Order List</th>
                          </tr>
                        </thead>
                        <tbody>
                          <?php
                                $items= mysqli_query($link,"SELECT rq_sl_no,c_code,sc_code,sc_name,mat_maker,mat_des,mat_qty,mat_unit FROM dept_inc_req WHERE slip_no=".$_GET['slipno']." AND gen_by_app=1 AND stock_app=0 ");
                                $count=1;
                                while($exe_sd = mysqli_fetch_array($items)) {
                                       ?>
                                    <tr id="even_<?=$count?>" class="even pointer">
                                   <!--td class="a-center "><input type="checkbox"  id="req_item_<?=$count?>" name="table_records" value="even_<?=$count?>||<?=$exe_sd['rq_sl_no']?>||<?=$exe_sd['sc_name']?>||<?=$exe_sd['mat_des']?>||<?=$exe_sd['mat_maker']?>"></td-->
                                
                                                 <td><?=$count?></td>
                                                 <td><?=$exe_sd['sc_name']?></td>
                                                 <td><?=$exe_sd['mat_maker']?> </td>
                                                 <td><?=$exe_sd['mat_des']?></td>
                                                 <td><?=$exe_sd['mat_qty']?></td>
                                                 <td><p id="stock_view_<?=$count?>" style="color:green;">click to know!</p></td>
                                                 <td><?=$exe_sd['mat_unit']?></td>
                                                 <td><button type="button" id="click"  class="btn btn-primary btn-xs click" name="click" onclick=" $('#stock_view_<?=$count?>,#avl_stock').load('check_item.php?sc=<?=$exe_sd['sc_code']?>');" >Click</button></td>
                                                 <td><button class="btn btn-info btn-xs mdetails" type="button" id="m_details<?=$count?>"  onclick="$('#fund_select').val('');$('#disp_more_details').load('dispatch_item.php?more=<?=$exe_sd['sc_code']?>');$('#row_more_deails').val(<?=$count?>); $('#dataModal_idetails').modal('show');">More Details</button></td>
                                                 <td><button class="btn btn-success btn-xs dispatch" style="display:block" type="button" id="dispatch_<?=$count?>"  value="even_<?=$count?>||<?=$exe_sd['rq_sl_no']?>||<?=$exe_sd['sc_name']?>||<?=$exe_sd['mat_des']?>||<?=$exe_sd['mat_maker']?>||<?=$exe_sd['mat_unit']?>||<?=$count?>||<?=$exe_sd['sc_code']?>||dispatch_<?=$count?>" onclick="itemdata(this.value)"  data-toggle="modal"   data-target="#dataModal_dispatch">Dispatch</button><button class="btn btn-danger btn-xs ftd" style="display:none" type="button" id="ftd_<?=$count?>"  value="even_<?=$count?>||<?=$exe_sd['rq_sl_no']?>||<?=$exe_sd['sc_name']?>||<?=$exe_sd['mat_des']?>||<?=$exe_sd['mat_maker']?>||<?=$exe_sd['mat_unit']?>||<?=$count?>||<?=$exe_sd['sc_code']?>||ftd_<?=$count?>"  data-toggle="modal"   data-target="#">Dispatch by Fund</button></td>
                                                <td><button type="" class="btn btn-warning btn-xs order">Add To Order List</button></td>
                                                
                                    </tr>
                                      <?php
                                       $count++;
                                       
                                       /*$('#stock_'<?=$count?>).load('check_item.php?cc=<?=$exe_sd['c_code']?>&sc=<?=$exe_sd['sc_code']?>');alert('ok');......*/
                                  }
                                  $dr_row=$count-1;
                                  //$_SESSION['stocki']=$dr_row;
                            ?>

                            
                        </tbody>

                      </table>
                        <div id="dis_msg"> 
                       
                        </div>
                    </div></div></div>
                      <div id="disp_view">
                        <center><input type="button" id='disp_btn' class="btn btn-info" value="Dispatched Item List"/></center>
                    </div>
                     <!--stock details start--> 
                     <div id="disp_stock" style="display:none;">
                      <div class="x_title">
                    <h2>Dispatched Item Details <small>check item details</small></h2>
                    <div class="clearfix"></div>
                  </div>   
                         <div class="table-responsive" id='disp_table'>
                             
                         </div>
                     </div>
                      <!--stock details stop-->
                     
                    </div>
            </div>
          </div>
        </div>
        <!-- more details start-->
         
          <div id="dataModal_idetails" class="modal fade" role="dialog">
              <div class="modal-dialog">
                  <div class="modal-content">
                  <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Item Stock Details:</h4>
                  </div>
                  <div class="modal-body" id="slip_details" >
                 <div class="table-responsive" id='disp_more_details'>
                             
                         </div>
                      <center><button type="button" id="sfd"  class="btn btn-success btn-xs sfd" name="sfd" value="" onclick="" >Select For Dispatch</button></center>
                      <input type="hidden" id="row_more_deails" readonly="" />
                      <input type="hidden" id="fund_select" readonly="" />
                  <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
              </div>
          </div>
          </div>
          </div>
         <!-- more details stop-->
                  <!-- dispatch start-->
          <div id="dataModal_dispatch" class="modal fade" role="dialog">
              <div class="modal-dialog">
                  <div class="modal-content">
                  <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Dispatch Details</h4>
                  </div>
                  <div class="modal-body" id="slip_details" >
                      <form id="dis_form" name="dis_form" method="get"  action="dispatch_item.php">
                          <input type="hidden" id="t_slno" class="form-control" readonly="" />
                          <input type="hidden" id="r_i_slno" class="form-control" readonly="" />
                          <div class="form-group">
                           <label class="control-label col-md-2 col-sm-1 col-xs-2">Item Name:</label>
                        <div class="col-md-5 col-sm-8 col-xs-8">
                            <input type="text" id="r_i_name" name="r_i_name" readonly=""  class="form-control col-md-7 col-xs-12">
                        </div>
                          <label class="control-label col-md-2 col-sm-3 col-xs-6">Availavle Stock:</label>
                        <div class="col-md-3 col-sm-2 col-xs-6" id="avl_stock">
                            <!--input type="text" id="avl_stock" name="avl_stock" readonly="" class="form-control col-md-7 col-xs-12" /-->             
                        </div>
                          
                      </div>
                          <br/><br/><br/>
                          <label>Required Item description:</label>
                          <input type="text" id="r_i_des" class="form-control" readonly="" /><br/>
                          <label>Dispatch Fund Type:</label>
                          <input type="text" id="diftype" class="form-control" readonly="" /><br/>
                          <!--select id="diftype" name="diftype" class="form-control" required="">
                                <option value="None">--select--</option>
                                <option value="CLJF">College Fund</option>
                                <option value="TEQIP-I">Technical Education Quality Improvement Programme (TEQIP-I)</option>
                                <option value="TEQIP-II">Technical Education Quality Improvement Programme (TEQIP-II)</option>                     
                             <option value="TEQIP-III">Technical Education Quality Improvement Programme (TEQIP-III)</option>
                            </select-->
                          <div id="set_d_details">
                          <div class="form-group">
                           <label class="control-label col-md-2 col-sm-1 col-xs-2" for="item-quantity">Total Item Quantity <span class="required">*</span>
                        </label>
                        <div class="col-md-5 col-sm-8 col-xs-8">
                          <input type="text" id="d_qty" name="d_qty" required="required"  class="form-control col-md-7 col-xs-12">
                        </div>
                          <label class="control-label col-md-2 col-sm-3 col-xs-3" for="item-unit">Unit <span class="required">*</span>
                        </label>
                        <div class="col-md-2 col-sm-2 col-xs-2">
                            <input type="text" id="d_unit" name="d_unit" readonly="" class="form-control col-md-7 col-xs-12" />             
                        </div>
                          
                      </div>
                              </div>
                      <br/><br/><br/>
                          <label>Dispatch description:</label>
                          <input type="text" class="form-control" id="d_i_des" />
                          <br/>
                          <p style="color:green">** For Multiple Fund Type Use This Below Field.</p>
                          <p style="color:green">** Specify Unique Quantity using ',' separation, Ex:- 2,3</p>
                          <div class="form-group">
                           <label class="control-label col-md-2 col-sm-1 col-xs-2" for="item-quantity">Item Quantity/Fund</label>
                        <div class="col-md-5 col-sm-8 col-xs-8">
                            <input type="text" id="fu_qty" name="fu_qty"  class="form-control col-md-7 col-xs-12">
                        </div>
                           <input type="button" class="btn btn-warning" id="unique_qty" name="unique_qty" value="Add Quantity"/>
                          </div>
                          <input type="hidden" id="fund_qty" name="fund_qty" />
                          <div id="fund_qty_msg" ></div>
                          <br/><br/><br/>
                          
                            <center> 
                                <!--input type="button" name="btn_qty" id="btn_qty" value="SET QYANTITY" class="btn btn-warning" /-->
                                <input type="submit" name="done" id="done" value="DONE" class="btn btn-success" /> </center><br />
                      <br/>
                      </form>
                      <center><div id="loading2" style="display: none;"><img src="./images/uploading.gif"><br></div></center>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
              </div>
          </div>
          </div>
          </div>
                  <!-- dispatch stop-->
                  
                   <!--dispatch by fund start-->
                  <div id="dataModal_dataModal_byfund" class="modal fade" role="dialog">
              <div class="modal-dialog">
                  <div class="modal-content">
                  <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Dispatch Item by Fund Type:</h4>
                  </div>
                  <div class="modal-body" id="slip_details" >
                           <label class="col-md-2 col-sm-1 col-xs-2">Fund Type:</label>
                        <div class="col-md-5 col-sm-8 col-xs-8">
                            <input type="text" id="f_name" name="f_name" readonly=""  class="col-md-7 col-xs-12">
                        </div>
                          <label class="col-md-2 col-sm-3 col-xs-6">Quantity</label>
                        <div class="col-md-3 col-sm-2 col-xs-6">
                            <input type="number" id="fd_qty" name="fd_qty" class="col-md-7 col-xs-12" />             
                        </div>
                      <center><button type="button" id="idef"  class="btn btn-success btn-xs idef" name="idbf" value=""  >SET</button></center>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
              </div>
          </div>
          </div>
          </div>
                  <!--dispatch by fund stop-->
        <!--script src="./plugins/jQuery/jquery-2.2.4.min.js"></script-->
         <script src="js/jquery.min.js"></script>
         <script src="js/jquery.form.js"></script> 
                 <script>
                   //  alert('ok');
                     var stk,c=0,ff=0,btn='',ricol,fandq=' ';
                     var row_1=<?=$dr_row?>;
                   //  var row=<?=$_SESSION['stocki']?>;
                   // var row=5;
                     var rslno=<?=$_GET['slipno']?>;
                        if(c==row_1)
                             {
                                 $('#req_table_details').hide(300);
                              }
                     function itemdata(value){
                                       // alert(value);
                                    var val=value.split('||');
                                        var rowid,id,des,maker,unit,name,col,instk,dft,spdc,icol;
                                        rowid=val[0];
                                        id=val[1];
                                        name=val[2];
                                        des="DESCRIPTION:-"+val[3];
                                        maker="MAKER:-"+val[4];
                                        unit=val[5];
                                        col=val[6];
                                        instk=val[7];
                                        btn=val[8];
                                        document.getElementById('t_slno').value=rowid;
                                        document.getElementById('r_i_slno').value=id;
                                        document.getElementById('r_i_name').value=name;
                                        document.getElementById('r_i_des').value=maker+'; '+des;
                                        document.getElementById('d_unit').value=unit;
                                        document.getElementById('d_i_des').value='MAKER:-___;  DESCRIPTION:-___';
                                        stk=$('#avl_stock').load('check_item.php?sc='+instk);
                                        dft=document.getElementById('row_more_deails').value;
                                        ricol=parseInt(col);
                                        icol=parseInt(dft);
                                        if(ricol!==icol)
                                        {
                                            document.getElementById('diftype').value=' ';
                                            document.getElementById('d_qty').value=' ';
                                            document.getElementById('fund_qty').value=' ';
                                            document.getElementById('fu_qty').value=' ';
                                        }                                           
                     }
                     
                     function view_disp()
                    {
                        var disp = document.getElementById("disp_stock");
                        //alert('ok'); 
                        if(disp.style.display=='none')
                            {
                                //alert("block");
                                disp.style.display='block';
                                 //$('#disp_stock').html(<meta http-equiv="refresh" content="0; url=item_approval.php" />);
                            }
                            else
                            {
                              //  alert("none");
                                disp.style.display='none';
                                 //$('#disp_stock').html(<meta http-equiv="refresh" content="0; url=item_approval.php" />);
                            }     
                    }
                     
                     
                     
                    $(document).ready(function(){
                      //  alert('ok');
                    //  alert('row='+row);
            /*more_details_start*/
                $('#sfd').click(function(){
                    if(confirm('Process Selected Item?'))
                    {
                     // var row=<?=$_SESSION['stocki']?>;
                     var row=$('#rowcount').val();
                    // alert('row='+row);
                        var num=row;  
                        //alert('row'+row);
                        //alert('num:'+num);
                        if(row>0){
                                 var i,fid='';
                                 for(i=1;i<=num;i++)
                                 {
                                  if($('#ch_'+i).prop("checked")==true)
                                    {
                                       // alert('true');
                                       // var value=$('#ch_'+i).val();
                                        var uiid=$('#iid_'+i).val();
                                       // var val=value.split('||');
                                       /* var dfund,ddate,spdate,rw,dfbt;
                                        dfund=val[0];
                                        ddate=val[1];
                                        rw=val[2];
                                        //alert(dfund);
                                        //alert(uiid);
                                        spdate=ddate.split('-');
                                        //alert(spdate[0]);
                                        //alert(spdate[1]);
                                        //alert(spdate[2]);
                                        //fid=fid+dfund+'/'+spdate[1]+'/'+rw+'/'+spdate[2];
                                       // fid=fid+dfund+'/'+spdate[0]+'/'+spdate[1]+'/'+spdate[2]+'/'+uiid;*/
                                        fid=fid+uiid;
                                        $('#fund_select,#diftype').val(fid);
                                        fid=fid+',';
                                    }
                                }
                               // alert(fid);
                                $('#dataModal_idetails').modal('hide');
                        }
                    }
                    else
                    {
                        return false;
                    }
                });
                
                /*more_details_stop*/
                
                                /*set quantity start*/
                $('#unique_qty').click(function(){
                       var fundid,valf,valfu,i=0,fuqty;
                       fundid=$('#diftype').val();
                       fuqty=$('#fu_qty').val();
                       if(fuqty !==' ' && fundid !==' '){
                      // alert(fundid);
                      // alert(fuqty);
                       valf=fundid.split(',');
                       valfu=fuqty.split(',');
                      $('#loading2').show();
                        while(valf[i]){
                         alert(valf[i]);
                        alert(valfu[i]);
                         $('#fund_qty_msg').load('dispatch_item.php?fid='+valf[i]+'&fiqty='+valfu[i]);
                        // fandq=fandq+valf[i]+'::'+valfu[i];
                        //fandq=fandq+':::';
                        i++;
                    }
                   // alert(typeof(fundid));
                   // alert(typeof(fandq));
                    fandq=fundid+'::'+fuqty;
                    $('#fund_qty').val(fandq);
                    $('#loading2').hide(300);
                }
                });
                /*set quantity stop*/
                
                /*dispatch_start*/      
                   $('#dis_form').ajaxForm({
			beforeSubmit:function(){
                                 var qty,d_des,slno,tslno,ftype,des_data,is,iq,valf=false,i=0,ftsp=null;
                                       $('#done').click(function(){
                                           tslno=$('#t_slno').val();
                                           slno=$('#r_i_slno').val();
                                           stk=stk.html();
                                           ftype=$('#diftype').val();
                                           qty=$('#d_qty').val();
                                           des_data=encodeURIComponent($('#d_i_des').val());
                                           stk=parseInt(stk);
                                           qty=parseInt(qty);
                                           if (stk>=qty)
                                           {
                                                    $('#loading2').show();
                                                     if(fandq===' ')
                                                     {
                                                         alert('ok');
                                                       $('#fu_qty').val(qty);
                                                         var uniqueqty=qty;
                                                         fandq=ftype+'::'+uniqueqty;
                                                        // alert(uniqueqty);
                                                         //alert(ftype);
                                                         alert(fandq);
                                                         //alert(typeof(fandq));
                                                        $('#fund_qty_msg').load('dispatch_item.php?fid='+ftype+'&fiqty='+uniqueqty);
                                                        document.getElementById('fu_qty').value=' ';
                                                      //  setTimeout(location.reload.bind(location), 500);
                                                     }
                                                     alert(fandq);
                                               $('#dis_msg').load('dispatch_item.php?sl='+slno+'&dqty='+qty+'&ddes='+des_data+'&ft='+ftype+'&fuqt='+fandq);
                                                      fandq=' ';
                                                            $('#'+tslno).hide(300);                
                                                            c=c+1;
                                                         // alert('c='+c);
                                                          //alert('row='+row_1);
                                                           if(c==row_1)
                                                                {
                                                                     $('#req_table_details').hide(300);
                                                                }    
                                           }
                                           else{
                                                   alert('Please,Check Available Stock!');
                                                   document.getElementById("dis_form").reset();
                                                   $('#dataModal_dispatch').modal('hide');
                                              }
                                });				
			},
			success:function(e){
                            $('#loading2').hide();
                            if(e!=null){  
                                
                             document.getElementById("dis_form").reset();
                             $('#dataModal_dispatch').modal('hide');
				$('#loading_up').hide();
                            }
			},
			error:function(e){
                         $('#loading2').hide(); 
                         document.getElementById("dis").innerHTML='<p align="center" class="alert alert-danger alert-dismissable" style="color:red;"><a class="close" data-dismiss="alert" aria-label="close">×</a>OOPS..!! Server Not Responding.</p>';  
			}
		}).submit();
               
                /*dispatch_stop*/ 
                
                /*display_start*/ 
                $('#disp_btn').click(function(){
                      var disp = document.getElementById("disp_stock");  
                      //alert('ok'); 
                        if(disp.style.display==='none')
                            {
                               // alert("block");
                               disp.style.display='block';
                               $('#disp_table').load('dispatch_item.php?display='+rslno);
                                 //$('#disp_stock').html(<meta http-equiv="refresh" content="0; url=item_approval.php" />);
                            }
                            else
                            {
                              // alert("none");
                                disp.style.display='none';
                             //$('#disp_stock').html(<meta http-equiv="refresh" content="0; url=item_approval.php" />);
                            }  
                });
                /*display_stop*/
                
                setTimeout(function(){
                document.getElementById("uqid").style.display = "none"; 
                }, 1000);
                                    setTimeout(function(){
                document.getElementById("dismsg").style.display = "none"; 
                }, 3000);
                    });
                 </script>

                 <!-- /page content -->
       <!-- footer content -->
        <footer>
          <div class="pull-right">
            BIET - Stock Management System <a href="#"></a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
    <!-- jQuery -->
    <!-- Bootstrap -->
    <script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="../vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="../vendors/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="../vendors/Chart.js/dist/Chart.min.js"></script>
    <!-- gauge.js -->
    <script src="../vendors/gauge.js/dist/gauge.min.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="../vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <!-- iCheck -->
    <script src="../vendors/iCheck/icheck.min.js"></script>
    <!-- Skycons -->
    <script src="../vendors/skycons/skycons.js"></script>
    <!-- Flot -->
    <script src="../vendors/Flot/jquery.flot.js"></script>
    <script src="../vendors/Flot/jquery.flot.pie.js"></script>
    <script src="../vendors/Flot/jquery.flot.time.js"></script>
    <script src="../vendors/Flot/jquery.flot.stack.js"></script>
    <script src="../vendors/Flot/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="../vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
    <script src="../vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
    <script src="../vendors/flot.curvedlines/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="../vendors/DateJS/build/date.js"></script>
    <!-- JQVMap -->
    <script src="../vendors/jqvmap/dist/jquery.vmap.js"></script>
    <script src="../vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
    <script src="../vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="../vendors/moment/min/moment.min.js"></script>
    <script src="../vendors/bootstrap-daterangepicker/daterangepicker.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="../build/js/custom.min.js"></script>
    
  </body>
</html>