<!DOCTYPE html>
<?php
    include './header.php';
    include './db_connect.php';
?>
        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>REQUISITION SLIP<small>Stock Management System</small></h3>
              </div>

              

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                      <h2>Your Order Details <small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                                          </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>SL NO.</th>
                          <th>Item Name</th>
                          <th>Quantity</th>
                          <th>Unit</th>
                          <th>Description</th>
                          
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <th scope="row">1</th>
                          <td>Mark</td>
                          <td>Otto</td>
                          <td>2</td>
                          <td>Otto</td>
                          
                        </tr>
                        <tr>
                          <th scope="row">2</th>
                          <td>Jacob</td>
                          <td>Thornton</td>
                          <td>8</td>
                          <td>Otto</td>
                          
                          
                        </tr>
                        <tr>
                          <th scope="row">3</th>
                          <td>Larry</td>
                          <td>the Bird</td>
                          <td>2</td>
                          <td>Otto</td>
                          
                        </tr>
                      </tbody>
                    </table>

                  </div>
                </div>
              </div>


              <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                      <h2>ADD YOUR REQUIRED ITEM<small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content"> 
                  

                      <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                       <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="gen_by">Requisition generated By <span class="required">*</span>
                        </label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="gen_by" id="gen_by" readonly="" required="required" class="form-control col-md-7 col-xs-12" value="<?php echo $_SESSION['smsname']; ?>">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="gen_by_desg">His/Her designation <span class="required">*</span>
                        </label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" id="gen_by_desg" name="gen_by_desg" readonly="" required="required" class="form-control col-md-7 col-xs-12" value="<?php echo $_SESSION['smsdesg']; ?>">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="gen_for">Material Required By <span class="required">*</span>
                        </label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" id="gen_for" name="gen_for" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="gen_for_desg">His/Her Designation<span class="required">*</span>
                        </label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <select class="select2_single form-control" tabindex="-1" name="gen_for_desg" id="gen_for_desg">
                            <option>--Select--</option>
                            <option value="HOD">HOD</option>
                            <option value="FAC">Faculty</option>
                            <option value="ACC">Accountant</option>
                            <option value="LA">Lab Assistant</option>
                            </select>                        
                        </div>
                      </div>
                      <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12">Choose Category<span class="required">*</span></label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                         <input type="hidden" name="c_name" id="c_name" class="form-control">
                          <select name="c_name_db" id="c_name_db" class="select2_single form-control" onclick="set_value(this.value)">
                             <option>--Select--</option>
                             <?php
                                    //echo category_name($link)
                                $q1= mysqli_query($link,"select c_name,c_code from category_master");
                                while($r1= mysqli_fetch_array($q1)){
                                ?>
                                <option value="<?=$r1['c_name'].'|'.$r1['c_code']?>"><?=$r1['c_name']?></option>
                                <?php
                                }
                                ?>
                          </select>
                        </div>
                      </div>
                          <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="c_code">Category Code 
                        </label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                            <input type="text" id="c_code" name="c_code" readonly="" class="form-control col-md-7 col-xs-12">
                        </div>
                      </div>
                      <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12">Item name<span class="required">*</span></label>
                        <div id="i_name_div"  class="col-md-9 col-sm-9 col-xs-12">
                        <!--input type="text" id="item_list" name="item_list" class="form-control"-->
                             <select id="item_list" name="item_list" class="form-control col-md-7 col-xs-12" >
                            
                            </select>
                        </div>

                      </div>

                        
                          
                          <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="mat_maker">Brand/Maker name 
                        </label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" id="mat_maker" name="mat_maker" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                      </div>
                          <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="mat_des">Description
                        </label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text"  id="mat_des" name="mat_des" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                          </div>
                          <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="mat_qty">Quantity<span class="required">*</span>
                        </label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                          <input type="number" min="1" id="mat_qty" name="mat_qty" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                              <!--<div class="form-group">-->
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="mat_unit">Unit<span class="required">*</span>
                        </label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                          <select id="mat_unit" name="mat_unit" class="select2_single form-control" tabindex="-1">
                             <option>--Select--</option>
                            <option value="">lit</option>
                            <option value="">ml</option>
                            <option value="">kg</option>
                            <option value="">gm</option>
                            <option value="">meter</option>
                            <option value="">foot</option>
                            <option value="">pices</option>
                            <option value="">coil</option>
                            <option value="">rim</option>
                            <option value="">pkt</option>
                            </select>
                        </div>
                          <!--</div>-->
                          </div>
                          
                          
                          
                      <div class="ln_solid">
                          <div class="clearfix"></div>
                      <center><button type="submit" class="btn btn-success">Add</button>
                      <button type="submit" class="btn btn-success">Reset</button></center>
                        </div>
                      

                    </form>
 
                    <!--<table class="table table-striped">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>First Name</th>
                          <th>Last Name</th>
                          <th>Username</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <th scope="row">1</th>
                          <td>Mark</td>
                          <td>Otto</td>
                          <td>@mdo</td>
                        </tr>
                        <tr>
                          <th scope="row">2</th>
                          <td>Jacob</td>
                          <td>Thornton</td>
                          <td>@fat</td>
                        </tr>
                        <tr>
                          <th scope="row">3</th>
                          <td>Larry</td>
                          <td>the Bird</td>
                          <td>@twitter</td>
                        </tr>
                      </tbody>
                    </table>-->

                  </div>
                </div>
              </div>

                <div class="clearfix"></div>
                    
            </div>
                </div>
              </div>
            </div>
          
        <!-- /page content -->

        <!-- footer content -->
        <?php
            include './footer.php';
        ?>
        <script src="./plugins/jQuery/jquery-2.2.4.min.js"></script>
                      <!--script>
                        function set_value(value){
                           var actval=value.split('|');
                           document.getElementById('c_name').value=actval[0];
                           document.getElementById('c_code').value=actval[1];
                           $('#item_list').load('ajax_item_list.php?cat='+actval[1]);
                        }
                        
                        </script-->  
                        <link href="select2-3.5.3/select2.css" rel="stylesheet" />
    <script src="select2-3.5.3/select2.js"></script>
    <script>
    $(document).ready(function() {
  $("#item_list").select2();
});
    </script>
        <!-- /footer content -->
        
        <!--script src="./plugins/jQuery/jquery-2.2.4.min.js"></script>
        <script>
          
            $(document).ready(function(){
                
                $('#c_code').change(function(){
                   var txt = $(this).val();
                        $.ajax({
                           url:"fetch.php",
                           method:"POST",
                           data:{search:txt},
                           dataType:"text",
                           success:function(data){
                                $('#i_name_db').html(data);
                            }
                       
                   });
               
                      
                   
                });
            });
        </script-->
      

    